### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '4

### ISSUE THREAD

**Issue by Duffyx** [yboetz/pyznap#18]
![image](https://user-images.githubusercontent.com/32487486/48305512-0c26ef00-e52c-11e8-95bd-0e52aad7af7a.png)

![image](https://user-images.githubusercontent.com/32487486/48305508-f5809800-e52b-11e8-8e81-677555b86a12.png)

![image](https://user-images.githubusercontent.com/32487486/48305509-fd403c80-e52b-11e8-82e0-bfce46421605.png)

**Comment by yboetz** [comment]
You have to remove the comments at the end of the lines. Lines starting with `#` will be ignored, but all other `#` will be included. So instead of just '4' your line actually says '4                # Keep 4 quarter.....', which cannot be converted to an int. I'll try to fix it that it gives a better error message.

**Comment by Duffyx** [comment]
Haha alright, thanks!

**Comment by yboetz** [comment]
Np, happened to other people as well :).
