### ISSUE TITLE
Graceful way to handle configparser requirement on Python 3.6+?

### ISSUE THREAD

**Issue by fryfrog** [yboetz/pyznap#37]
I package pyznap for Arch Linux in the AUR, but I don't really *use* it. While updating to 1.2.0, I realized I couldn't actually run it... below output is the result. But our Python 3.7.3 has `configparser` built in. I can run `python` and then `import configparser` no problem.

Eventually, I settled on just using `sed` to remove the line from your `requires.txt` after the `python setup.py install`, but it seems like there has to be a smarter way.

```
0 ✓ fryfrog@apollo ~ $ pyznap
Traceback (most recent call last):
  File "/usr/bin/pyznap", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'configparser>=3.5.0' distribution was not found and is required by pyznap
```
```
1 ✗ fryfrog@apollo ~ $ cat $( which pyznap )
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'pyznap==1.2.0','console_scripts','pyznap'
__requires__ = 'pyznap==1.2.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('pyznap==1.2.0', 'console_scripts', 'pyznap')()
    )
```
```
0 ✓ fryfrog@apollo ~ $ python
Python 3.7.3 (default, Jun 24 2019, 04:54:02)
[GCC 9.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import configparser
>>>
```

**Comment by eli-schwartz** [comment]
A proper solution which you could upstream would be to use https://www.python.org/dev/peps/pep-0508/#environment-markers to make configparser only an install_requires for python versions that don't have it builtin.

**Comment by yboetz** [comment]
I just noticed that I can actually also `import configparser` in Python 3.5 and 3.6, it is a built in module. I don't know why I put it in the `install_requires`.... I'll update this later and release a fix. Thanks!

**Comment by yboetz** [comment]
Fixed in the latest release.

**Comment by fryfrog** [comment]
Thanks :)

**Comment by eli-schwartz** [comment]
`configparser` (going as far back as python 3.0) is just the renamed `ConfigParser` from python 2.7, but it exists on PyPI as well, as a backport of the latest stdlib functionality.

If the goal was to actually support python 2.7 and make use of the new features in configparser, then an install_requires with an environment marker specifying `'configparser;python_version<="2.7"'` would be the way to go. If the goal was to support python 3.4 but require configparser features first introduced in python 3.5, then the way to go would be to continue using `'configparser>=3.5.0'` but also require a python version via `'configparser>=3.5.0;python_version<="3.4"'`, with the caveat that you cannot actually `import configparser`; you need to

```
try:
    from backports.configparser import ...
except:
    from configparser import ...
```

in order to ensure that python 3.0 - 3.7 import the PyPI-sourced install_requires when it exists (and which is required to exist for 3.0 - 3.4) while falling back to the stdlib in the case of python 3.5 - 3.7 where it does not need to exist and no other project in your python site-packages happens to have installed a newer version.

**Comment by yboetz** [comment]
Actually only python 3.5+ is supported (see #10). As `configparser` is standard in 3.5+ just removing the dependency is the easiest, no need to worry about supporting older versions.

**Comment by eli-schwartz** [comment]
That's fine, just thought I'd give a bit of context on why there is both a stdlib and PyPI module here (since @fryfrog summoned me and therefore I was here).

P.S. If you only support python >= 3.5, you may wish to enforce that through something a bit stronger than a statement in the README. See https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

**Comment by yboetz** [comment]
Thanks for the context, I was really a bit confused why there is a configparser module on PyPI when it's already built in. That is also why initially I had it as a `install_requires`.

I will add the `python_requires` in the next release, thanks!
