### ISSUE TITLE
large sync to slow

### ISSUE THREAD

**Issue by svennd** [yboetz/pyznap#55]
Hey,

I been struggling with this "large" transfer; I have 17TB on my server, and want to keep this in sync with another server;  The problem is, the data sync takes so long that pyznap generates snapshots faster then it could send over; eventually resulting in the sync stopping; Most of this data is stale, but it got imported in one go.

I thought I disable pyznap and run a snap and a send after it; This worked; After that I reran snap & send; but this fails as there is no "common" snapshot anymore the weekly got removed and the remote was lagging behind. 

Now I have the data on both servers (but no common snapshots); Can I fix this w/o sending another 17TB over the line ?

**Comment by yboetz** [comment]
Oh, this seems to be a worst case scenario... As far as I know there is no way to do incremental sync if there are no common snapshots anymore, and the whole transfer has to be redone. Without common snapshots, ZFS has no way of knowing which data is already on the remote and you need a full sync. 

If most of the data is stale, you could create a new dataset and from now on only work on that and only sync that. Though this might not be preferable for you...

Do you know why the transfer stopped when you let pyznap still generate snapshots? Just creating new snapshots should not affect the running zfs send, as it will just send over an existing snapshot that are not affected by new ones. If you delete old snapshots though then you might run into problems, since pyznap might want to delete old snapshots that are still being used for zfs send. In this case either disable pyznap or set up a policy such that older snapshots are kept for longer. It is extremely important that you keep old snapshots for longer than your usual backup period. In case of this large and I guess quite long transfer I would advice to keep a long history of snapshots, just so you don't run out of common ones...

**Comment by svennd** [comment]
Well, its only part of the story; The servers where connected through a 10GBit line during install, and sync'd; then one was shipped off and couldn't sync for a 2 week period; When it was shipped over a large part of the data was changed (a better compression) the sync failed as there was no common snapshot; So we wiped the remote one and send it over; So for future, if I understand correctly : 

So the fix is to start all over and increase the snapshot duration well over the turnover for snapshots. (monthly or yearly ?)

Thanks for your help !

**Comment by yboetz** [comment]
Yes, you should always have snapshot turnover much longer than your backup frequency. I usually sync all my datasets daily to my remote server, and even on non-important data I keep 7 daily, 4 weekly and 3 monthly snapshots, just to be sure that even if I'm not able to sync for a longer time I can still do an incremental sync.

If in the future you know that you will not be able to sync for a longer time, you can temporarily increase the policy so pyznap keeps some old snapshots around for the eventual incremental sync. Once regular syncs are working again, you can then decrease the number of old snapshots again.

**Comment by svennd** [comment]
thanks!
