### ISSUE TITLE
issue on running?

### ISSUE THREAD

**Issue by killmasta93** [yboetz/pyznap#56]
Hi,
Currently installed on proxmox, but im getting this error

```
root@prometheus4:/media# ./pyznap.conf 
./pyznap.conf: line 14: [rpool/data]: No such file or directory
./pyznap.conf: line 15: frequent: command not found
./pyznap.conf: line 16: snap: command not found
./pyznap.conf: line 17: clean: command not found
root@prometheus4:/media# zfs list
NAME                       USED  AVAIL  REFER  MOUNTPOINT
rpool                      269G  3.25T    96K  /rpool
rpool/ROOT                1.06G  3.25T    96K  /rpool/ROOT
rpool/ROOT/pve-1          1.06G  3.25T  1.06G  /
rpool/data                 268G  3.25T    96K  /rpool/data
rpool/data/vm-103-disk-0  16.5G  3.25T  16.5G  -
rpool/data/vm-103-disk-1   207G  3.25T   207G  -
rpool/data/vm-104-disk-0  25.8G  3.25T  25.8G  -
rpool/data/vm-105-disk-0  9.22G  3.25T  9.21G  -
rpool/data/vm-116-disk-0  9.61G  3.25T  8.99G  -

```

These are the steps i did 

```
apt-get install python3.5
apt-get install python3-pip
pip3 install pyznap
 /usr/local/bin/pyznap setup -p /media/
```

**Comment by yboetz** [comment]
Hi

The `pyznap.conf` is the config file, not the executable you need to run. The executable is in your case under ` /usr/local/bin/pyznap`. When running

     /usr/local/bin/pyznap setup -p /media/

this will create the sample config file under `/media/pyznap.conf`. You need to adapt it to your datasets and create a policy in there. E.g. if you want to take regular snapshots of your rpool you can do something like

    [rpool]
    hourly = 24
    daily = 7
    weekly = 4
    monthly = 6
    snap = yes
    clean = yes

All options are explained in the sample config file, and you can adapt it to your needs. To run pyznap then you need to run

     /usr/local/bin/pyznap setup --config /media/pyznap.conf snap

Since you put the config file in a non-standard directory, you need to specify that when running with the flag `--config /media/pyznap.conf`. I would advice to put config files in the standard directory `/etc/pyznap/` though, so you don't always have to do that. For that just run ` /usr/local/bin/pyznap setup` without any `-p` flag and it will create the sample config under `/etc/pyznap/pyznap.conf`.

**Comment by killmasta93** [comment]
yes sorry i had to run manually this 

`pyznap --config /media/pyznap.conf snap`
