### ISSUE TITLE
issue sending to another zfs pool?

### ISSUE THREAD

**Issue by killmasta93** [yboetz/pyznap#60]
Hi
I currently trying to test out sending the pool datasets to another ZFS disks
this is my config

```
[rpool/data]
frequent = 30
snap = yes
clean = yes
dest = vmbaks

```

the error im getting is this
```

root@prometheus3:~# pyznap send 
Jun 07 23:48:43 INFO: Starting pyznap...
Jun 07 23:48:43 INFO: Sending snapshots...
Jun 07 23:48:43 ERROR: No snapshots on rpool/data, cannot send...
Jun 07 23:48:43 ERROR: No snapshots on rpool/data/vm-124-disk-0, cannot send...
Jun 07 23:48:43 INFO: Finished successfully...
```

My question is that when sending the send command wouldn't it first send the full data disk then create the snapshot? or only the snapshot?

Thank you

**Comment by yboetz** [comment]
You first need to create at least one snapshot to use `zfs send`. ZFS can only send snapshots, not datasets. So if you first run `pyznap snap` it will create a `frequent` snapshot as per your policy, then you can send this one via `pyznap send`. Be aware though that you always need to keep at least one snapshot in common between your source and dest. So if you delete too many snapshot on your source so that you don't have any matching snapshots on your dest, then pyznap can no longer send incrementally and you need to destroy and resend to your dest. It is advisable to also keep multiple longer term snapshots (daily, weekly, monthly), not only frequent ones.

**Comment by killmasta93** [comment]
Thanks for the reply, so im running first the pyznap snap then the pyznap send which so far is working great, but the part of the clean only is cleaning on the rpool but no the where the destination not sure if im missing something? 
Thank you

**Comment by yboetz** [comment]
That is by design, as you might want to keep more snapshots on the destination. To clean the destination you have to make a separate entry in your config file, e.g.:

  [vmbaks]
  frequent = 60
  clean = yes

**Comment by killmasta93** [comment]
Thanks for the reply, that did the trick, but quick question currently got this email alert 

```
Jun 15 14:00:01 ERROR: Error while sending to vmbaks: umount: /vmbaks/dumps: target is busy -         (In some cases useful info about processes that -          use the device is found by lsof(8) or fuser(1).) - cannot unmount '/vmbaks/dumps': umount failed...
Null message body; hope that's ok
```

**Comment by yboetz** [comment]
Sorry for the late response. It seems the destination dataset is busy, but it should be as it should only be used for pyznap backups. Make sure pyznap send is done before you call `pyznap snap --clean` on the destination dataset, and maybe try to manually unmount the dataset before running pyznap again.

**Comment by killmasta93** [comment]
Thanks for the reply, what i had to do, is to create another dataset within the pool
because i had vmbaks/dumps as a file storage so i created vmbaks/data and put in the VMs so far haven't got that alert ill post back if i get it

**Comment by yboetz** [comment]
That is what you have to do, you cannot use a backup dataset for something else, as it needs to be an exact copy of the source.
