### ISSUE TITLE
Issue on sending snapshot?

### ISSUE THREAD

**Issue by killmasta93** [yboetz/pyznap#83]
HI,
I was wondering if someone could shed some light on the issue im having.
Currently i have ZFS pool called data and i need to migrate to another pool called data2 within the same machine

this is the pool i have
```
root@cloud:~# zfs list
NAME    USED  AVAIL     REFER  MOUNTPOINT
data   4.86T  1.86T     4.86T  /data
data2  6.38M  5.77T     1.50M  /data2
```
and the config 
```
[/data]
frequent = 64
snap = yes
clean = yes
dest = data2

[/data2]
hourly = 64
clean = yes
```
i first ran pyznap snap
```
root@cloud:~# zfs list -t snapshot
NAME                                       USED  AVAIL     REFER  MOUNTPOINT
data@pyznap_2021-09-04_15:49:13_frequent   786K      -     4.86T  -
```
then ran pyzsnap send 

but i get this, it seems that its not sending the info to data2

```
root@cloud:~# pyznap send
Sep 04 15:56:42 INFO: Starting pyznap...
Sep 04 15:56:42 INFO: Sending snapshots...
Sep 04 15:56:42 INFO: data is up to date...
Sep 04 15:56:42 INFO: Finished successfully...

```

Thank you

**Comment by yboetz** [comment]
Two things:
- There should not be any leading slashes for datasets in the config, so you should have `[data]` instead of `[/data]`. I'm not sure if that could be the cause of your problem, but something I noticed.
- You keep 64 frequent snapshots on `data` and 64 hourly on `data2`. That will lead to a mismatch since all frequent snapshots on `data2` will be deleted and then you don't have any common snapshots.

Apart from that everything looks ok and should work as you expected it to. Try to fix those two things and see if it works then. You could also try to send without a config, i.e. do `pyznap send -s data -d data2` and see if that works.

**Comment by killmasta93** [comment]
Thank you so much for the reply, that did the trick remove the / 
I will also change the 64 frequent thanks for pointing that out,
Out of curiosity, is it possible to run dry run and possible to show the ETA?

**Comment by yboetz** [comment]
Great, glad that solved it. A dry run is not possible currently, so there is no way to show an ETA before actually starting the zfs send. Duration also depends on quite a lot of things (speed of both drives, internet connection if send over ssh, ...).
