### ISSUE TITLE
Get property error

### ISSUE THREAD

**Issue by neic** [yboetz/pyznap#9]
I'm getting the following error on a newly installed system.

```sh
(venv) root@wiply:/home/neic/pyznap# pyznap --config ./pyznap.conf snap
Aug 14 15:21:27 INFO: Starting pyznap...
Aug 14 15:21:27 INFO: Taking snapshots...
Aug 14 15:21:27 INFO: Taking snapshot tank/neic@pyznap_2018-08-14_15:21:27_hourly...
Aug 14 15:21:27 INFO: Taking snapshot tank/neic@pyznap_2018-08-14_15:21:27_frequent...
Aug 14 15:21:27 INFO: Cleaning snapshots...
Aug 14 15:21:27 INFO: Finished successfully...

(venv) root@wiply:/home/neic/pyznap# pyznap --config ./pyznap.conf send
Aug 14 15:21:37 INFO: Starting pyznap...
Aug 14 15:21:37 INFO: Sending snapshots...
Aug 14 15:21:37 ERROR: Command '['zfs', 'get', '-H', '-p', '-d', '0', 'type', '/tank/neic']' returned non-zero exit status 1.
Aug 14 15:21:37 INFO: Finished successfully...

```

`zfs get -H -p -d 0 type /tank/neic` works fine:
```sh
(venv) root@wiply:/home/neic/pyznap# zfs get -H -p -d 0 type /tank/neic
tank/neic       type    filesystem      -
```
<details>

My `~/pyznap.conf`:
```conf
[tank]
frequent = 4
hourly = 24
daily = 7
weekly = 4
monthly = 6
yearly = 1
snap = no


[tank/neic]
snap = yes
dest = ssh:22:root@192.168.0.3:/tank/neic
dest_keys = /root/.ssh/id_rsa
```

My system info:
```sh
(venv) root@wiply:/home/neic/pyznap# pip list
Package       Version
------------- -------
asn1crypto    0.24.0 
bcrypt        3.1.4  
cffi          1.11.5 
configparser  3.5.0  
cryptography  2.3    
idna          2.7    
paramiko      2.4.1  
pip           18.0   
pkg-resources 0.0.0  
pyasn1        0.4.4  
pycparser     2.18   
PyNaCl        1.2.1  
pyznap        1.0.1  
setuptools    39.0.1 
six           1.11.0 
(venv) root@wiply:/home/neic/pyznap# apt show zfsutils-linux 
Package: zfsutils-linux
Version: 0.7.5-1ubuntu16.3
# […]
(venv) root@wiply:/home/neic/pyznap# lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```
</details>

**Comment by yboetz** [comment]
I think the error comes from your config entry

    dest = ssh:22:root@192.168.0.3:/tank/neic

You always have to write the root pool without leading slash, so this should be

    dest = ssh:22:root@192.168.0.3:tank/neic

The unclear error message is because I haven't implemented all ZFS error messages yet, so when there is an error that I haven't implemented it just raises the general `returned non-zero exit status 1` error.

When I try the command `zfs get -H -p -d 0 type /tank` on my system I get an error with the message `/tank: No such file or directory`. But `zfs get -H -p -d 0 type tank` works without problem. I also work on Ubuntu 18.04 with zfsutils-linux v0.7.5.

One more thing: Why are you trying to send `tank/neic` to itself? This will not work, pyznap will always say `tank/neic is up to date...`, as the snapshots are identical.

**Comment by neic** [comment]
Great. The `/`  was indeed the issue. Thanks a lot, both for this and for the software in general. 😃

**Comment by yboetz** [comment]
No problem, glad to help :).
